### ISSUE TITLE
Metrics labels and values in loki logs

### ISSUE THREAD

**Issue by deathalt** [metrico/qryn#423]
Qryn Prometheus metrics duplicated in loki requests with labels and their values

![image](https://github.com/metrico/qryn/assets/35489816/67e99215-eb6a-4b5b-b370-2171e986b04a)
![image](https://github.com/metrico/qryn/assets/35489816/c395f0c8-37bc-445a-b7e2-fc5c23ebb24e)

it's not a problem when you can add a filter, such as `{job="loki", level=~""}` but if the log doesn't have a level, you have to come up with other ways to filter logs from metrics.
And then the number of labels starts to grow for loki as well.

**Comment by lmangani** [comment]
A change is upcoming to avoid this side effect. @akvlad will provide updates once ready

**Comment by akvlad** [comment]
@deathalt the feature is inside the branch https://github.com/metrico/qryn/tree/feat_423 .
Merge and release will be done shortly.

**Comment by deathalt** [comment]
updated qryn version to 3.1.5, visually nothing has changed.
![image](https://github.com/metrico/qryn/assets/35489816/1324aaa3-3f25-468a-86ed-a560a0c95b1d)

**Comment by bcarlock-mycarrier** [comment]
Just reporting in- I updated our qryn instance to 3.1.5-bun and we're still seeing this issue.
![image](https://github.com/metrico/qryn/assets/148160053/6a069d61-1681-4294-b7b1-ef8209705f2b)
![image](https://github.com/metrico/qryn/assets/148160053/7f24d6b1-e4eb-4d6b-8619-460101d6b84e)

**Comment by akvlad** [comment]
Should be fixed in 3.2.0

**Comment by bcarlock-mycarrier** [comment]
@akvlad I updated to 3.2.0 and we're still seeing metrics appear as logs.

**Comment by lmangani** [comment]
Thanks for the report @bcarlock-mycarrier could you provide some examples for a better understanding?

**Comment by bcarlock-mycarrier** [comment]
Sure:
deployment - 
![image](https://github.com/metrico/qryn/assets/148160053/1ba4a419-887e-4507-9497-58c13741cf64)
![image](https://github.com/metrico/qryn/assets/148160053/f53a30a4-1791-487a-9a7c-75363c5f2ccd)

**Comment by bcarlock-mycarrier** [comment]
I'd be happy to provide more information if you can tell me what might be helpful. Right now we have two different qryn instances, one for metrics, one for logs in order to avoid this problem.

**Comment by akvlad** [comment]
@bcarlock-mycarrier @deathalt  let me recap what was changed in 3.2.0.

The extra env config was added to qryn: `DISTINGUISH_LOGS_METRICS=1`. 
After the environment is provided, the newly ingested information starts to be distinguished between logs and metrics.
All the existing information is still present in the both datasources. 
Please recheck the config env vars for qryn.

I believe that it appeared somewhere in the new documentation. Will recheck and add if needed. 
Sorry for the inconvenience.

**Comment by deathalt** [comment]
@akvlad 

I have the same behavior.
```
CLICKHOUSE_SERVER: chproxy.chproxy.svc
  CLICKHOUSE_PORT: 9090
  CLICKHOUSE_DB: qryn
  CLICKHOUSE_AUTH: default:
  CLICKHOUSE_PROTO: http
  CLICKHOUSE_TIMEFIELD: record_datetime
  CLUSTER_NAME: shard
  BULK_MAXAGE: 4000
  BULK_MAXSIZE: 10000000
  BULK_MAXCACHE: 100000
  LABELS_DAYS: 7
  SAMPLES_DAYS: 7
  HOST: 0.0.0.0.0
  PORT: 3100
  FASTIFY_BODYLIMIT: 5242880
  FASTIFY_REQUESTTIMEOUT: 30000
  FASTIFY_MAXREQUESTS: 0
  FASTIFY_METRICS: true
  NODE_OPTIONS: "--max-old-space-size=61440"
  DISTINGUISH_LOGS_METRICS: 1
```
fresh metrics are still in the logs.
![image](https://github.com/metrico/qryn/assets/35489816/da895a01-1c46-4989-91ec-5a7290fb0a96)

**Comment by bcarlock-mycarrier** [comment]
DISTINGUISH_LOGS_METRICS=1 seems to have solved the problem for us. Which brings up the question, under what circumstance would you want this turned off? It doesn't seem like the sort of thing you'd usually put behind a feature flag.

**Comment by lmangani** [comment]
@bcarlock-mycarrier I think its safe to say once we're past the testing confirmations it will become a default

**Comment by bcarlock-mycarrier** [comment]
Makes sense. I'm not sure if this is related or not, but I'm seeing somewhat reduced query performance after enabling that.

**Comment by lmangani** [comment]
Interesting. @akvlad is any performance impact expected? or might this be due to the "dual-stack" support of both old and new types?

**Comment by akvlad** [comment]
The type support is an extra `IN` in terms of the sql.
IN is incredibly fast in clickhouse, like 100M comparisons a sec. But anyway it has its cost.

**Comment by bcarlock-mycarrier** [comment]
We just turned this back on yesterday. The current count is 232,913, so not a ton honestly. 

```
{"level":30,"time":1706633942002,"pid":24,"hostname":"qryn-metrics-reader-9977db669-72jv9","name":"qryn","reqId":"req-1j","req":{"method":"GET","url":"/api/v1/labels?start=1706612340&end=1706634000","hostname":"qryn-metrics-reader.monitoring:3100","remoteAddress":"10.2.2.247","remotePort":34502},"msg":"incoming request"}
{"level":20,"time":1706633942003,"pid":24,"hostname":"qryn-metrics-reader-9977db669-72jv9","name":"qryn","reqId":"req-1j","msg":"GET /loki/api/v1/label"}
SELECT DISTINCT key FROM time_series_gin WHERE date >= toDate(FROM_UNIXTIME(intDiv(1706612340000000000, 1000000000))) AND date <= toDate(FROM_UNIXTIME(intDiv(1706634000000000000, 1000000000))) AND type IN (0,0) FORMAT JSON
{"level":30,"time":1706633942393,"pid":24,"hostname":"qryn-metrics-reader-9977db669-72jv9","name":"qryn","reqId":"req-1j","res":{"statusCode":200},"responseTime":390.80939300358295,"msg":"request completed"}
```

**Comment by bcarlock-mycarrier** [comment]
I have a quick addition to this issue. Since updating and enabling DISTINGUISH_LOGS_METRICS we've also noticed some strangeness related to the Loki interface label correlation. The first label selected is always a label from logging. The second label is always what appears to be a metric tag. The third label tends to be a log label again.
![labelissues](https://github.com/metrico/qryn/assets/148160053/5e98fcbc-35d1-4cc8-8535-1482ffb95ab8)

**Comment by lmangani** [comment]
Thanks for the report @bcarlock-mycarrier 👍 
@akvlad and the team will investigate and provide feedback

**Comment by lmangani** [comment]
@bcarlock-mycarrier we cannot reproduce this condition. Please open a separate issue with all the case details. If you're running multiple instances or multiple readers/writers make sure they are all featuring the same settings.

**Comment by bcarlock-mycarrier** [comment]
> @bcarlock-mycarrier we cannot reproduce this condition. Please open a separate issue with all the case details. If you're running multiple instances or multiple readers/writers make sure they are all featuring the same settings.

Will do. As of this morning it isn't happening any more. I'm guessing the labels were cached from prior to having DISTINGUISH_LOGS_METRICS enabled. If I can get it to happen again I'll post a new issue.

**Comment by lmangani** [comment]
This should be resolved in the latest releases. Please reopen if the issue is still relevant.

**Comment by mk-raven** [comment]
The problem was stayed with metrics labels in logs.
